// Centralized PWA web manifest + brand colors.
//
// The app chrome is intentionally neutral (primary = Tailwind neutral-800), so
// the PWA `theme_color` is reconciled to that neutral primary instead of the
// old purple (#863bff), which contradicted the UI. Brand colors are imported
// from `@remindit/common` — the shared brand source of truth (DESIGN.md §2) —
// and consumed here and by `scripts/generate-favicons.ts`, so the manifest and
// the generated icons stay in sync from a single source of truth.

import {
  BRAND_BACKGROUND_COLOR,
  BRAND_COLOR,
  BRAND_NAME,
} from "@remindit/common"
import type { WebAppManifest } from "rsbuild-plugin-pwa"

const ANDROID_SIZES = [36, 48, 72, 96, 144, 192, 256, 384, 512] as const

// Typed against the plugin's own manifest type so literal fields
// (`form_factor`, `purpose`, `display`, ...) can't widen to `string`.
export const WEB_APP_MANIFEST: WebAppManifest = {
  name: BRAND_NAME,
  short_name: BRAND_NAME,
  description: "Local-first reminders that work offline.",
  theme_color: BRAND_COLOR,
  background_color: BRAND_BACKGROUND_COLOR,
  display: "standalone",
  start_url: "/",
  // Richer install UI: up to 8 screenshots, ≥320px and ≤3840px each, max dim
  // ≤2.3× min dim. All `narrow` shots share one aspect ratio (1320x2868);
  // all `wide` shots share another (1280x720). Generated by
  // scripts/generate-mobile-screenshot.ts.
  screenshots: [
    {
      src: "/screenshot-mobile-list-light.png",
      sizes: "1320x2868",
      type: "image/png",
      form_factor: "narrow",
      label: "Shopping list (light)",
    },
    {
      src: "/screenshot-mobile-list-dark.png",
      sizes: "1320x2868",
      type: "image/png",
      form_factor: "narrow",
      label: "Shopping list (dark)",
    },
    {
      src: "/screenshot-mobile-catalog-light.png",
      sizes: "1320x2868",
      type: "image/png",
      form_factor: "narrow",
      label: "Catalog",
    },
    {
      src: "/screenshot-mobile-profile-light.png",
      sizes: "1320x2868",
      type: "image/png",
      form_factor: "narrow",
      label: "Profile",
    },
    {
      src: "/screenshot-desktop-list-light.png",
      sizes: "1280x720",
      type: "image/png",
      form_factor: "wide",
      label: "Shopping list",
    },
    {
      src: "/screenshot-desktop-catalog-light.png",
      sizes: "1280x720",
      type: "image/png",
      form_factor: "wide",
      label: "Catalog",
    },
    {
      src: "/screenshot-desktop-profile-light.png",
      sizes: "1280x720",
      type: "image/png",
      form_factor: "wide",
      label: "Profile",
    },
    {
      src: "/screenshot-desktop-history-light.png",
      sizes: "1280x720",
      type: "image/png",
      form_factor: "wide",
      label: "History",
    },
  ],
  icons: [
    {
      src: "/remindit-icon.svg",
      sizes: "any",
      type: "image/svg+xml",
      purpose: "any",
    },
    {
      src: "/remindit-icon-maskable.svg",
      sizes: "any",
      type: "image/svg+xml",
      purpose: "maskable",
    },
    // Standard android-chrome PNGs (purpose "any") — generated by scripts/generate-favicons.ts
    ...ANDROID_SIZES.map((size) => ({
      src: `/android-chrome-${size}x${size}.png`,
      sizes: `${size}x${size}`,
      type: "image/png",
      purpose: "any",
    })),
    // Maskable android-chrome PNGs (purpose "maskable") — full-bleed safe-zone source
    ...ANDROID_SIZES.map((size) => ({
      src: `/android-chrome-maskable-${size}x${size}.png`,
      sizes: `${size}x${size}`,
      type: "image/png",
      purpose: "maskable",
    })),
  ],
}
