// Centralized PWA web manifest + brand colors.
//
// The app chrome is intentionally neutral (primary = Tailwind neutral-800), so
// the PWA `theme_color` is reconciled to that neutral primary instead of the
// old purple (#863bff), which contradicted the UI. Both `rsbuild.config.ts`
// (the generated manifest) and `scripts/generate-favicons.ts` (favicon
// generation) consume these values, so the manifest and the generated icons
// stay in sync from a single source of truth.

// Tailwind neutral-800 — the app's actual primary in light mode.
export const PWA_THEME_COLOR = "#262626"
export const PWA_BACKGROUND_COLOR = "#ffffff"

const ANDROID_SIZES = [36, 48, 72, 96, 144, 192, 256, 384, 512] as const

export const WEB_APP_MANIFEST = {
  name: "Remindit",
  short_name: "Remindit",
  description: "Local-first reminders that work offline.",
  theme_color: PWA_THEME_COLOR,
  background_color: PWA_BACKGROUND_COLOR,
  display: "standalone",
  start_url: "/",
  icons: [
    {
      src: "/remindit-icon.svg",
      sizes: "any",
      type: "image/svg+xml",
      purpose: "any",
    },
    {
      src: "/remindit-icon-maskable.svg",
      sizes: "any",
      type: "image/svg+xml",
      purpose: "maskable",
    },
    // Standard android-chrome PNGs (purpose "any") — generated by scripts/generate-favicons.ts
    ...ANDROID_SIZES.map((size) => ({
      src: `/android-chrome-${size}x${size}.png`,
      sizes: `${size}x${size}`,
      type: "image/png",
      purpose: "any",
    })),
    // Maskable android-chrome PNGs (purpose "maskable") — full-bleed safe-zone source
    ...ANDROID_SIZES.map((size) => ({
      src: `/android-chrome-maskable-${size}x${size}.png`,
      sizes: `${size}x${size}`,
      type: "image/png",
      purpose: "maskable",
    })),
  ],
}
