import { defineConfig } from "@rsbuild/core"
import { pluginReact } from "@rsbuild/plugin-react"
import { pluginTailwindcss } from "@rsbuild/plugin-tailwindcss"
import { pluginPWA } from "rsbuild-plugin-pwa"
import * as QRCode from "qrcode"

export default defineConfig({
  html: {
    template: "public/index.html",
  },
  alias: {
    "@": "./src",
  },
  server: {
    host: "0.0.0.0",
    printUrls({ urls }) {
      urls.map((url) => console.log(`  ➜  ${url}`))
      console.log()
      // use only the last URL to generate the QR code
      QRCode.toString(
        urls.pop() ?? urls[0],
        { type: "terminal" },
        (err, url) => {
          if (err) throw err
          console.log(url)
        }
      )
    },
  },
  plugins: [
    pluginReact({
      reactCompiler: true,
    }),
    pluginTailwindcss(),
    pluginPWA({
      dev: true,
      webAppManifest: {
        content: {
          name: "Remindit",
          short_name: "Remindit",
          description: "Local-first reminders that work offline.",
          theme_color: "#863bff",
          background_color: "#ffffff",
          display: "standalone",
          start_url: "/",
          icons: [
            {
              src: "/remindit-icon.svg",
              sizes: "any",
              type: "image/svg+xml",
              purpose: "any",
            },
            {
              src: "/remindit-icon-maskable.svg",
              sizes: "any",
              type: "image/svg+xml",
              purpose: "maskable",
            },
            // Standard android-chrome PNGs (purpose "any") — generated by scripts/generate-favicons.ts
            {
              src: "/android-chrome-36x36.png",
              sizes: "36x36",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/android-chrome-48x48.png",
              sizes: "48x48",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/android-chrome-72x72.png",
              sizes: "72x72",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/android-chrome-96x96.png",
              sizes: "96x96",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/android-chrome-144x144.png",
              sizes: "144x144",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/android-chrome-192x192.png",
              sizes: "192x192",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/android-chrome-256x256.png",
              sizes: "256x256",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/android-chrome-384x384.png",
              sizes: "384x384",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/android-chrome-512x512.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "any",
            },
            // Maskable android-chrome PNGs (purpose "maskable") — full-bleed safe-zone source
            {
              src: "/android-chrome-maskable-36x36.png",
              sizes: "36x36",
              type: "image/png",
              purpose: "maskable",
            },
            {
              src: "/android-chrome-maskable-48x48.png",
              sizes: "48x48",
              type: "image/png",
              purpose: "maskable",
            },
            {
              src: "/android-chrome-maskable-72x72.png",
              sizes: "72x72",
              type: "image/png",
              purpose: "maskable",
            },
            {
              src: "/android-chrome-maskable-96x96.png",
              sizes: "96x96",
              type: "image/png",
              purpose: "maskable",
            },
            {
              src: "/android-chrome-maskable-144x144.png",
              sizes: "144x144",
              type: "image/png",
              purpose: "maskable",
            },
            {
              src: "/android-chrome-maskable-192x192.png",
              sizes: "192x192",
              type: "image/png",
              purpose: "maskable",
            },
            {
              src: "/android-chrome-maskable-256x256.png",
              sizes: "256x256",
              type: "image/png",
              purpose: "maskable",
            },
            {
              src: "/android-chrome-maskable-384x384.png",
              sizes: "384x384",
              type: "image/png",
              purpose: "maskable",
            },
            {
              src: "/android-chrome-maskable-512x512.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "maskable",
            },
          ],
        },
      },
    }),
  ],
})
