/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125DownloadRouteImport } from './routes/{-$locale}/download'
import { Route as Char123LocaleChar125FeaturesRouteImport } from './routes/{-$locale}/features'

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DownloadRoute =
  Char123LocaleChar125DownloadRouteImport.update({
    id: '/{-$locale}/download',
    path: '/{-$locale}/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125FeaturesRoute =
  Char123LocaleChar125FeaturesRouteImport.update({
    id: '/{-$locale}/features',
    path: '/{-$locale}/features',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}/download': typeof Char123LocaleChar125DownloadRoute
  '/{-$locale}/features': typeof Char123LocaleChar125FeaturesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/download': typeof Char123LocaleChar125DownloadRoute
  '/{-$locale}/features': typeof Char123LocaleChar125FeaturesRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/download': typeof Char123LocaleChar125DownloadRoute
  '/{-$locale}/features': typeof Char123LocaleChar125FeaturesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/{-$locale}/download' | '/{-$locale}/features' | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$locale}/download' | '/{-$locale}/features' | '/{-$locale}'
  id:
    | '__root__'
    | '/{-$locale}/download'
    | '/{-$locale}/features'
    | '/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125DownloadRoute: typeof Char123LocaleChar125DownloadRoute
  Char123LocaleChar125FeaturesRoute: typeof Char123LocaleChar125FeaturesRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/download': {
      id: '/{-$locale}/download'
      path: '/{-$locale}/download'
      fullPath: '/{-$locale}/download'
      preLoaderRoute: typeof Char123LocaleChar125DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/features': {
      id: '/{-$locale}/features'
      path: '/{-$locale}/features'
      fullPath: '/{-$locale}/features'
      preLoaderRoute: typeof Char123LocaleChar125FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125DownloadRoute: Char123LocaleChar125DownloadRoute,
  Char123LocaleChar125FeaturesRoute: Char123LocaleChar125FeaturesRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
